version: '3.1'

networks:
  ctunc:

services:

  # Local Services -----------------------

  ct-lets-coding-config-server-app:
    image: lets-coding-config-server-app:0.0.2
    container_name: ct-lets-coding-config-server-app
    restart: always
    networks:
      - ctunc
    environment:
      CONFIG_SERVER_URL: http://ct-lets-coding-config-server-app:8761
      SERVER_PORT: 8761
    ports:
      - '8761:8761'


